import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h2>Título da página 2</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec mauris orci, commodo a rhoncus vel, condimentum eu orci. In ultrices pretium metus, et volutpat magna mattis ac. Nunc pellentesque gravida urna, a rhoncus dolor viverra imperdiet. Integer facilisis eros vel est dignissim commodo. Sed auctor egestas enim et volutpat. Nullam bibendum efficitur euismod. Phasellus condimentum neque eu ex vehicula, vel vehicula risus condimentum. Ut leo ligula, blandit in libero ac, gravida tempus leo. Aliquam porta auctor magna eget fermentum. Nam et vestibulum sapien, in ullamcorper arcu. Duis lobortis, justo ac vulputate gravida, enim mi placerat metus, ac ullamcorper libero eros id turpis. Sed nec nulla in eros facilisis tristique eget ac tellus. Phasellus ornare diam in fringilla feugiat. Curabitur lacinia auctor aliquet.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec mauris orci, commodo a rhoncus vel, condimentum eu orci. In ultrices pretium metus, et volutpat magna mattis ac. Nunc pellentesque gravida urna, a rhoncus dolor viverra imperdiet. Integer facilisis eros vel est dignissim commodo. Sed auctor egestas enim et volutpat. Nullam bibendum efficitur euismod. Phasellus condimentum neque eu ex vehicula, vel vehicula risus condimentum. Ut leo ligula, blandit in libero ac, gravida tempus leo. Aliquam porta auctor magna eget fermentum. Nam et vestibulum sapien, in ullamcorper arcu. Duis lobortis, justo ac vulputate gravida, enim mi placerat metus, ac ullamcorper libero eros id turpis. Sed nec nulla in eros facilisis tristique eget ac tellus. Phasellus ornare diam in fringilla feugiat. Curabitur lacinia auctor aliquet.</p>
      </main>
    </>
  )
}
