import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h2>Título da página 1</h2>
        <p>Para ajudar ao próximo , começamos ajudando quem está perto de nós !
          assim iniciamos uma corrente de ajuda que beneficiará muitas pessoas , o mundo todo .

          Um dos principais oncologistas do Brasil, o médico Lucas da Siva ( fictício ) se dedicou ao departamento de oncologia urológica robotica do Hospital A.C. Camargo.

          Ele organizou médicos voluntários e parceiros para lançar, o maior centro de tratamento gratuito para o câncer urológico com a extração da próstata, na cidade de São Paulo.
        </p>

        <p>A instituição tem cerca de 5 mil homens atendidos anualmente, entre sessões de quimioterapia, consultas, procedimentos ambulatoriais, cirurgias, e outros.

          Meu marido foi atendido lá , não pagamos nada , e ainda um robô de última geração o operou com 3 furinhos apenas no abdômen.

          Além de diagnosticar e tratar o câncer , o grupo atua no desenvolvimento do ensino e pesquisa sobre o tema.
        </p>

        <p>
          São pessoas assim , que colocam a ajuda , o voluntário acima do lucro que ajudam o mundo a ser melhor
        </p>
      </main>
    </>
  )
}
